name: build

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 10 * * *' # everyday at 10am

jobs:
  docker:
    strategy:
      matrix:
        include:
          - version: 4.4.2-P1
            tag: stable
          - version: 4.1-ESV-R16-P1
            tag: esv

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/heilerich/isc-dhcpd
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=${{ matrix.tag }}
            type=semver,enable=true,value=v${{ matrix.version }},pattern={{version}}
            type=semver,enable=true,value=v${{ matrix.version }},pattern={{major}}.{{minor}}
            type=semver,enable=true,value=v${{ matrix.version }},pattern={{major}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            DHCPD_VERSION=${{ matrix.version }}
